using static BitMagic.Decompiler.Addressing;

namespace BitMagic.Decompiler;

public static class Addressing
{
    public enum AddressMode
    {
        Implied,
        Accumulator,
        Immediate,
        Absolute,
        XIndexAbsolute,
        YIndexAbsolute,
        AbsoluteIndirect,
        AbsoluteXIndexIndirect,
        ZeroPage,
        XIndexedZeroPage,
        YIndexedZeroPage,
        ZeroPageIndirect,
        XIndexZeroPageIndirect,
        ZeroPageIndirectYIndexed,
        Relative,
        ZeroPageRelative
    }

    public static string GetModeText(AddressMode addressMode, int value, int currentAddress) => addressMode switch
    {
        AddressMode.Implied => "",
        AddressMode.Accumulator => "",
        AddressMode.Immediate => $"#${value & 0xff:X2}",
        AddressMode.Absolute => $"${value:X4}",
        AddressMode.XIndexAbsolute => $"${value:X4}, x",
        AddressMode.YIndexAbsolute => $"${value:X4}, y",
        AddressMode.AbsoluteIndirect => $"(${value:X4})",
        AddressMode.AbsoluteXIndexIndirect => $"(${value:X4}, x)",
        AddressMode.ZeroPage => $"${value & 0xff:X2}",
        AddressMode.XIndexedZeroPage => $"${value & 0xff:X2}, x",
        AddressMode.YIndexedZeroPage => $"${value & 0xff:X2}, y",
        AddressMode.ZeroPageIndirect => $"(${value & 0xff:X2})",
        AddressMode.XIndexZeroPageIndirect => $"(${value & 0xff:X2}, x)",
        AddressMode.ZeroPageIndirectYIndexed => $"(${value & 0xff:X2}), y",
        AddressMode.Relative => $"${(sbyte)(value & 0xff) + currentAddress + 2:X4}",
        AddressMode.ZeroPageRelative => $"${value & 0xff:X2}, ${(sbyte)((value & 0xff00) >> 8) + currentAddress + 3:X4}",
        _ => "??"
    };

    public static string GetModeText(AddressMode addressMode, string value, int currentAddress) => addressMode switch
    {
        AddressMode.Implied => "",
        AddressMode.Accumulator => "",
        AddressMode.Immediate => $"#{value}",
        AddressMode.Absolute => value,
        AddressMode.XIndexAbsolute => $"{value}, x",
        AddressMode.YIndexAbsolute => $"{value}, y",
        AddressMode.AbsoluteIndirect => $"({value})",
        AddressMode.AbsoluteXIndexIndirect => $"({value}, x)",
        AddressMode.ZeroPage => $"{value}",
        AddressMode.XIndexedZeroPage => $"{value}, x",
        AddressMode.YIndexedZeroPage => $"{value}, y",
        AddressMode.ZeroPageIndirect => $"({value})",
        AddressMode.XIndexZeroPageIndirect => $"({value}, x)",
        AddressMode.ZeroPageIndirectYIndexed => $"({value}), y",
        AddressMode.Relative => value,
      //  AddressMode.ZeroPageRelative => $"${value & 0xff:X2}, ${(sbyte)((value & 0xff00) >> 8) + currentAddress + 3:X4}",
        _ => "??"
    };

    public static string GetPrimaryValue(AddressMode addressMode, int value, int currentAddress) => addressMode switch
    {
        AddressMode.Implied => "",
        AddressMode.Accumulator => "",
        AddressMode.Immediate => $"#${value & 0xff:X2}",
        AddressMode.Absolute => $"${value:X4}",
        AddressMode.XIndexAbsolute => $"${value:X4}",
        AddressMode.YIndexAbsolute => $"${value:X4}",
        AddressMode.AbsoluteIndirect => $"(${value:X4})",
        AddressMode.AbsoluteXIndexIndirect => $"${value:X4}",
        AddressMode.ZeroPage => $"${value & 0xff:X2}",
        AddressMode.XIndexedZeroPage => $"${value & 0xff:X2}",
        AddressMode.YIndexedZeroPage => $"${value & 0xff:X2}",
        AddressMode.ZeroPageIndirect => $"${value & 0xff:X2}",
        AddressMode.XIndexZeroPageIndirect => $"${value & 0xff:X2}",
        AddressMode.ZeroPageIndirectYIndexed => $"${value & 0xff:X2}",
        AddressMode.Relative => $"${(sbyte)(value & 0xff) + currentAddress + 2:X4}",
        AddressMode.ZeroPageRelative => $"${value & 0xff:X2}",
        _ => "??"
    };

    public static string GetSecondaryValue(AddressMode addressMode, int value, int currentAddress) => addressMode switch
    {
        AddressMode.ZeroPageRelative => $"${(sbyte)((value & 0xff00) >> 8) + currentAddress + 3:X2}",
        _ => ""
    };

    public static string GetModeSymbol(AddressMode addressMode, string symbol, string symbolb) => addressMode switch
    {
        AddressMode.Implied => "",
        AddressMode.Accumulator => "",
        AddressMode.Immediate => $"{symbol}",
        AddressMode.Absolute => $"{symbol}",
        AddressMode.XIndexAbsolute => $"{symbol}, x",
        AddressMode.YIndexAbsolute => $"{symbol}, y",
        AddressMode.AbsoluteIndirect => $"({symbol})",
        AddressMode.AbsoluteXIndexIndirect => $"({symbol}, x)",
        AddressMode.ZeroPage => $"{symbol}",
        AddressMode.XIndexedZeroPage => $"{symbol}, x",
        AddressMode.YIndexedZeroPage => $"{symbol}, y",
        AddressMode.ZeroPageIndirect => $"({symbol})",
        AddressMode.XIndexZeroPageIndirect => $"({symbol}, x)",
        AddressMode.ZeroPageIndirectYIndexed => $"({symbol}), y",
        AddressMode.Relative => $"{symbol}",
        AddressMode.ZeroPageRelative => $"{symbol}, {symbolb}",
        _ => "??"
    };

    public static (int Value, int ValueB) GetModeValue(AddressMode addressMode, int value, int currentAddress) => addressMode switch
    {
        AddressMode.Implied => (value, 0),
        AddressMode.Accumulator => (value, 0),
        AddressMode.Immediate => (value, 0),
        AddressMode.Absolute => (value, 0),
        AddressMode.XIndexAbsolute => (value, 0),
        AddressMode.YIndexAbsolute => (value, 0),
        AddressMode.AbsoluteIndirect => (value, 0),
        AddressMode.AbsoluteXIndexIndirect => (value, 0),
        AddressMode.ZeroPage => (value, 0),
        AddressMode.XIndexedZeroPage => (value, 0),
        AddressMode.YIndexedZeroPage => (value, 0),
        AddressMode.ZeroPageIndirect => (value, 0),
        AddressMode.XIndexZeroPageIndirect => (value, 0),
        AddressMode.ZeroPageIndirectYIndexed => (value, 0),
        AddressMode.Relative => ((sbyte)(value & 0xff) + currentAddress + 2, 0),
        AddressMode.ZeroPageRelative => (value & 0xff, ((value & 0xff00) >> 8) + currentAddress + 3),
        _ => (-1, -1)
    };

    public static int GetInstructionLenth(AddressMode addressMode) => addressMode switch
    {
        AddressMode.Implied => 1,
        AddressMode.Accumulator => 1,
        AddressMode.Immediate => 2,
        AddressMode.Absolute => 3,
        AddressMode.XIndexAbsolute => 3,
        AddressMode.YIndexAbsolute => 3,
        AddressMode.AbsoluteIndirect => 3,
        AddressMode.AbsoluteXIndexIndirect => 3,
        AddressMode.ZeroPage => 2,
        AddressMode.XIndexedZeroPage => 2,
        AddressMode.YIndexedZeroPage => 2,
        AddressMode.ZeroPageIndirect => 2,
        AddressMode.XIndexZeroPageIndirect => 2,
        AddressMode.ZeroPageIndirectYIndexed => 2,
        AddressMode.Relative => 2,
        AddressMode.ZeroPageRelative => 3,
        _ => -1
    };
}

public static class OpCodes
{
    public static (string OpCode, Addressing.AddressMode AddressMode) GetOpcode(int code) => code switch
    {
        0x69 => ("ADC", AddressMode.Immediate),
        0x6D => ("ADC", AddressMode.Absolute),
        0x7D => ("ADC", AddressMode.XIndexAbsolute),
        0x79 => ("ADC", AddressMode.YIndexAbsolute),
        0x65 => ("ADC", AddressMode.ZeroPage),
        0x75 => ("ADC", AddressMode.XIndexedZeroPage),
        0x72 => ("ADC", AddressMode.ZeroPageIndirect),
        0x61 => ("ADC", AddressMode.XIndexZeroPageIndirect),
        0x71 => ("ADC", AddressMode.ZeroPageIndirectYIndexed),
        0x29 => ("AND", AddressMode.Immediate),
        0x2D => ("AND", AddressMode.Absolute),
        0x3D => ("AND", AddressMode.XIndexAbsolute),
        0x39 => ("AND", AddressMode.YIndexAbsolute),
        0x25 => ("AND", AddressMode.ZeroPage),
        0x35 => ("AND", AddressMode.XIndexedZeroPage),
        0x32 => ("AND", AddressMode.ZeroPageIndirect),
        0x21 => ("AND", AddressMode.XIndexZeroPageIndirect),
        0x31 => ("AND", AddressMode.ZeroPageIndirectYIndexed),
        0x0A => ("ASL", AddressMode.Accumulator),
        0x0E => ("ASL", AddressMode.Absolute),
        0x1E => ("ASL", AddressMode.XIndexAbsolute),
        0x6 => ("ASL", AddressMode.ZeroPage),
        0x16 => ("ASL", AddressMode.XIndexedZeroPage),
        0x0F => ("BBR0", AddressMode.ZeroPageRelative),
        0x1F => ("BBR1", AddressMode.ZeroPageRelative),
        0x2F => ("BBR2", AddressMode.ZeroPageRelative),
        0x3F => ("BBR3", AddressMode.ZeroPageRelative),
        0x4F => ("BBR4", AddressMode.ZeroPageRelative),
        0x5F => ("BBR5", AddressMode.ZeroPageRelative),
        0x6F => ("BBR6", AddressMode.ZeroPageRelative),
        0x7F => ("BBR7", AddressMode.ZeroPageRelative),
        0x8F => ("BBS0", AddressMode.ZeroPageRelative),
        0x9F => ("BBS1", AddressMode.ZeroPageRelative),
        0xAF => ("BBS2", AddressMode.ZeroPageRelative),
        0xBF => ("BBS3", AddressMode.ZeroPageRelative),
        0xCF => ("BBS4", AddressMode.ZeroPageRelative),
        0xDF => ("BBS5", AddressMode.ZeroPageRelative),
        0xEF => ("BBS6", AddressMode.ZeroPageRelative),
        0xFF => ("BBS7", AddressMode.ZeroPageRelative),
        0x90 => ("BCC", AddressMode.Relative),
        0xB0 => ("BCS", AddressMode.Relative),
        0xF0 => ("BEQ", AddressMode.Relative),
        0x89 => ("BIT", AddressMode.Immediate),
        0x2C => ("BIT", AddressMode.Absolute),
        0x3C => ("BIT", AddressMode.XIndexAbsolute),
        0x24 => ("BIT", AddressMode.ZeroPage),
        0x34 => ("BIT", AddressMode.XIndexedZeroPage),
        0x30 => ("BMI", AddressMode.Relative),
        0xD0 => ("BNE", AddressMode.Relative),
        0x10 => ("BPL", AddressMode.Relative),
        0x80 => ("BRA", AddressMode.Relative),
        0x0 => ("BRK", AddressMode.Implied),
        0x50 => ("BVC", AddressMode.Relative),
        0x70 => ("BVS", AddressMode.Relative),
        0x18 => ("CLC", AddressMode.Implied),
        0xD8 => ("CLD", AddressMode.Implied),
        0x58 => ("CLI", AddressMode.Implied),
        0xB8 => ("CLV", AddressMode.Implied),
        0xC9 => ("CMP", AddressMode.Immediate),
        0xCD => ("CMP", AddressMode.Absolute),
        0xDD => ("CMP", AddressMode.XIndexAbsolute),
        0xD9 => ("CMP", AddressMode.YIndexAbsolute),
        0xC5 => ("CMP", AddressMode.ZeroPage),
        0xD5 => ("CMP", AddressMode.XIndexedZeroPage),
        0xD2 => ("CMP", AddressMode.ZeroPageIndirect),
        0xC1 => ("CMP", AddressMode.XIndexZeroPageIndirect),
        0xD1 => ("CMP", AddressMode.ZeroPageIndirectYIndexed),
        0xE0 => ("CPX", AddressMode.Immediate),
        0xEC => ("CPX", AddressMode.Absolute),
        0xE4 => ("CPX", AddressMode.ZeroPage),
        0xC0 => ("CPY", AddressMode.Immediate),
        0xCC => ("CPY", AddressMode.Absolute),
        0xC4 => ("CPY", AddressMode.ZeroPage),
        0x3A => ("DEC", AddressMode.Accumulator),
        0xCE => ("DEC", AddressMode.Absolute),
        0xDE => ("DEC", AddressMode.XIndexAbsolute),
        0xC6 => ("DEC", AddressMode.ZeroPage),
        0xD6 => ("DEC", AddressMode.XIndexedZeroPage),
        0xCA => ("DEX", AddressMode.Implied),
        0x88 => ("DEY", AddressMode.Implied),
        0x49 => ("EOR", AddressMode.Immediate),
        0x4D => ("EOR", AddressMode.Absolute),
        0x5D => ("EOR", AddressMode.XIndexAbsolute),
        0x59 => ("EOR", AddressMode.YIndexAbsolute),
        0x45 => ("EOR", AddressMode.ZeroPage),
        0x55 => ("EOR", AddressMode.XIndexedZeroPage),
        0x52 => ("EOR", AddressMode.ZeroPageIndirect),
        0x41 => ("EOR", AddressMode.XIndexZeroPageIndirect),
        0x51 => ("EOR", AddressMode.ZeroPageIndirectYIndexed),
        0x1A => ("INC", AddressMode.Accumulator),
        0xEE => ("INC", AddressMode.Absolute),
        0xFE => ("INC", AddressMode.XIndexAbsolute),
        0xE6 => ("INC", AddressMode.ZeroPage),
        0xF6 => ("INC", AddressMode.XIndexedZeroPage),
        0xE8 => ("INX", AddressMode.Implied),
        0xC8 => ("INY", AddressMode.Implied),
        0x4C => ("JMP", AddressMode.Absolute),
        0x6C => ("JMP", AddressMode.AbsoluteIndirect),
        0x7C => ("JMP", AddressMode.AbsoluteXIndexIndirect),
        0x20 => ("JSR", AddressMode.Absolute),
        0xA9 => ("LDA", AddressMode.Immediate),
        0xAD => ("LDA", AddressMode.Absolute),
        0xBD => ("LDA", AddressMode.XIndexAbsolute),
        0xB9 => ("LDA", AddressMode.YIndexAbsolute),
        0xA5 => ("LDA", AddressMode.ZeroPage),
        0xB5 => ("LDA", AddressMode.XIndexedZeroPage),
        0xB2 => ("LDA", AddressMode.ZeroPageIndirect),
        0xA1 => ("LDA", AddressMode.XIndexZeroPageIndirect),
        0xB1 => ("LDA", AddressMode.ZeroPageIndirectYIndexed),
        0xA2 => ("LDX", AddressMode.Immediate),
        0xAE => ("LDX", AddressMode.Absolute),
        0xBE => ("LDX", AddressMode.YIndexAbsolute),
        0xA6 => ("LDX", AddressMode.ZeroPage),
        0xB6 => ("LDX", AddressMode.YIndexedZeroPage),
        0xA0 => ("LDY", AddressMode.Immediate),
        0xAC => ("LDY", AddressMode.Absolute),
        0xBC => ("LDY", AddressMode.XIndexAbsolute),
        0xA4 => ("LDY", AddressMode.ZeroPage),
        0xB4 => ("LDY", AddressMode.XIndexedZeroPage),
        0x4A => ("LSR", AddressMode.Accumulator),
        0x4E => ("LSR", AddressMode.Absolute),
        0x5E => ("LSR", AddressMode.XIndexAbsolute),
        0x46 => ("LSR", AddressMode.ZeroPage),
        0x56 => ("LSR", AddressMode.XIndexedZeroPage),
        0xEA => ("NOP", AddressMode.Implied),
        0x9 => ("ORA", AddressMode.Immediate),
        0x0D => ("ORA", AddressMode.Absolute),
        0x1D => ("ORA", AddressMode.XIndexAbsolute),
        0x19 => ("ORA", AddressMode.YIndexAbsolute),
        0x5 => ("ORA", AddressMode.ZeroPage),
        0x15 => ("ORA", AddressMode.XIndexedZeroPage),
        0x12 => ("ORA", AddressMode.ZeroPageIndirect),
        0x1 => ("ORA", AddressMode.XIndexZeroPageIndirect),
        0x11 => ("ORA", AddressMode.ZeroPageIndirectYIndexed),
        0x48 => ("PHA", AddressMode.Implied),
        0x8 => ("PHP", AddressMode.Implied),
        0xDA => ("PHX", AddressMode.Implied),
        0x5A => ("PHY", AddressMode.Implied),
        0x68 => ("PLA", AddressMode.Implied),
        0x28 => ("PLP", AddressMode.Implied),
        0xFA => ("PLX", AddressMode.Implied),
        0x7A => ("PLY", AddressMode.Implied),
        0x7 => ("RMB0", AddressMode.ZeroPage),
        0x17 => ("RMB1", AddressMode.ZeroPage),
        0x27 => ("RMB2", AddressMode.ZeroPage),
        0x37 => ("RMB3", AddressMode.ZeroPage),
        0x47 => ("RMB4", AddressMode.ZeroPage),
        0x57 => ("RMB5", AddressMode.ZeroPage),
        0x67 => ("RMB6", AddressMode.ZeroPage),
        0x77 => ("RMB7", AddressMode.ZeroPage),
        0x2A => ("ROL", AddressMode.Accumulator),
        0x2E => ("ROL", AddressMode.Absolute),
        0x3E => ("ROL", AddressMode.XIndexAbsolute),
        0x26 => ("ROL", AddressMode.ZeroPage),
        0x36 => ("ROL", AddressMode.XIndexedZeroPage),
        0x6A => ("ROR", AddressMode.Accumulator),
        0x6E => ("ROR", AddressMode.Absolute),
        0x7E => ("ROR", AddressMode.XIndexAbsolute),
        0x66 => ("ROR", AddressMode.ZeroPage),
        0x76 => ("ROR", AddressMode.XIndexedZeroPage),
        0x40 => ("RTI", AddressMode.Implied),
        0x60 => ("RTS", AddressMode.Implied),
        0xE9 => ("SBC", AddressMode.Immediate),
        0xED => ("SBC", AddressMode.Absolute),
        0xFD => ("SBC", AddressMode.XIndexAbsolute),
        0xF9 => ("SBC", AddressMode.YIndexAbsolute),
        0xE5 => ("SBC", AddressMode.ZeroPage),
        0xF5 => ("SBC", AddressMode.XIndexedZeroPage),
        0xF2 => ("SBC", AddressMode.ZeroPageIndirect),
        0xE1 => ("SBC", AddressMode.XIndexZeroPageIndirect),
        0xF1 => ("SBC", AddressMode.ZeroPageIndirectYIndexed),
        0x38 => ("SEC", AddressMode.Implied),
        0xF8 => ("SED", AddressMode.Implied),
        0x78 => ("SEI", AddressMode.Implied),
        0x87 => ("SMB0", AddressMode.ZeroPage),
        0x97 => ("SMB1", AddressMode.ZeroPage),
        0xA7 => ("SMB2", AddressMode.ZeroPage),
        0xB7 => ("SMB3", AddressMode.ZeroPage),
        0xC7 => ("SMB4", AddressMode.ZeroPage),
        0xD7 => ("SMB5", AddressMode.ZeroPage),
        0xE7 => ("SMB6", AddressMode.ZeroPage),
        0xF7 => ("SMB7", AddressMode.ZeroPage),
        0x8D => ("STA", AddressMode.Absolute),
        0x9D => ("STA", AddressMode.XIndexAbsolute),
        0x99 => ("STA", AddressMode.YIndexAbsolute),
        0x85 => ("STA", AddressMode.ZeroPage),
        0x95 => ("STA", AddressMode.XIndexedZeroPage),
        0x92 => ("STA", AddressMode.ZeroPageIndirect),
        0x81 => ("STA", AddressMode.XIndexZeroPageIndirect),
        0x91 => ("STA", AddressMode.ZeroPageIndirectYIndexed),
        0xDB => ("STP", AddressMode.Implied),
        0x8E => ("STX", AddressMode.Absolute),
        0x86 => ("STX", AddressMode.ZeroPage),
        0x96 => ("STX", AddressMode.YIndexedZeroPage),
        0x8C => ("STY", AddressMode.Absolute),
        0x84 => ("STY", AddressMode.ZeroPage),
        0x94 => ("STY", AddressMode.XIndexedZeroPage),
        0x9C => ("STZ", AddressMode.Absolute),
        0x9E => ("STZ", AddressMode.XIndexAbsolute),
        0x64 => ("STZ", AddressMode.ZeroPage),
        0x74 => ("STZ", AddressMode.XIndexedZeroPage),
        0xAA => ("TAX", AddressMode.Implied),
        0xA8 => ("TAY", AddressMode.Implied),
        0x1C => ("TRB", AddressMode.Absolute),
        0x14 => ("TRB", AddressMode.ZeroPage),
        0x0C => ("TSB", AddressMode.Absolute),
        0x4 => ("TSB", AddressMode.ZeroPage),
        0xBA => ("TSX", AddressMode.Implied),
        0x8A => ("TXA", AddressMode.Implied),
        0x9A => ("TXS", AddressMode.Implied),
        0x98 => ("TYA", AddressMode.Implied),
        0xCB => ("WAI", AddressMode.Implied),
        0xDC => ("LDD", AddressMode.Absolute),
        0xFC => ("LDD", AddressMode.Absolute),
        _ => ("", (Addressing.AddressMode)(-1))
    };
}